import Head from "next/head";
import Body from "../components/Body/Body";
import Booking from "../components/Booking/Booking";
import Hero from "../components/Hero/Hero";
// import Place from "../components/Place/Place";
import taxi_image from "./../public/taxi.png";
import woman_image from "./../public/woman.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Office</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
        />
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiqx0MaSS3QybaU4NH9iehcbro6r92nD8&libraries=places"></script>

      </Head>

      <Body>
        {/* <div className='mt-5 mb-3 hero_cover'>
          

          <marquee direction="right" width="100%">
            <img src={taxi_image.src} className="img-fluid" />
          </marquee>

          <img src={woman_image.src} className="img-fluid woman" />
          </div> */}
        <Hero />
        <Booking />
        {/* <Place /> */}
        
        <div className="container mt-5">
          <div className="row">
            <div className="col-md-12 text-center"></div>
            <div className="col-md-6">
              <div className="hero-section">
                <h1>
                  Holiday Cab
                  <br />
                  Booking
                </h1>
                <p>
                  EXPERIENCE THE MOST HASSLE
                  <br /> FREE FLIGHT BOOKING
                  <br />
                  AND GET GREAT DEALS WITH
                  <br /> REASONABLE RATES
                </p>
                <h3>
                  Great Deals
                  <br /> And Great Offers
                </h3>
                <p>
                  <strong>
                    with reasonable rates in top airlince and destinations
                  </strong>
                </p>
              </div>
            </div>
            <div className="col-md-6"></div>
          </div>
        </div>
      </Body>
    </>
  );
}
